# Generated by Django 5.2.9 on 2026-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AutoInsurance.com', max_length=100)),
                ('phone_number', models.CharField(default='(866) 843-5386', max_length=20)),
                ('hero_title', models.CharField(default='Affordable Car Insurance Starts Here', max_length=200)),
                ('hero_subtitle', models.TextField(default='Compare quotes in minutes and maximize savings on a policy that’s right for you. Rates as low as $29/month*')),
                ('hero_button_text', models.CharField(default='Continue', max_length=50)),
                ('footer_text', models.TextField(default='AutoInsurance.com © 2026. All Rights Reserved.')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
