# Generated by Django 5.2.9 on 2026-01-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_email_siteconfig_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
