# Generated by Django 5.2.9 on 2026-01-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_home_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='companies/')),
                ('order', models.IntegerField(default=0)),
                ('is_show_on_home', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['order'],
            },
        ),
    ]
