# Generated by Django 5.2.9 on 2026-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_description_company_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.CharField(default='12130 Millennium Drive, Ste 600 Los Angeles, CA 90094', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_disclaimer',
            field=models.TextField(default='The Site is owned and operated by AutoInsurance.com. AutoInsurance.com is an insurance provider matching service and not an insurance broker or insurance company. Not all insurance companies are able to provide you with a quote. Make sure to compare carrier rates and fees as they can vary between insurance companies and will depend upon the state in which you reside. Additionally, any savings you receive will depend upon your driving history and other factors as determined by the insurance companies giving you quotes. None of the insurance companies with whom you may be matched through the site sponsor, endorse, or are in any way affiliated with AutoInsurance.com or this site.'),
        ),
    ]
