# Generated by Django 5.2.9 on 2026-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_default_contact_footerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
