# Generated by Django 5.2.9 on 2026-01-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_footerpage_content_footerpage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpage',
            name='layout',
            field=models.CharField(choices=[('center', 'Center (max-width)'), ('full', 'Full width')], default='center', max_length=10),
        ),
    ]
