# Generated by Django 5.2.9 on 2026-01-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_faqcategory_faqpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpost',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_photo',
            field=models.ImageField(blank=True, upload_to='faq/authors/'),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faqpost',
            name='author_website_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='FaqImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.faqpost')),
            ],
            options={
                'verbose_name': 'FAQ Image',
                'verbose_name_plural': 'FAQ Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
