# Generated by Django 5.2.9 on 2026-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_faqpost_author_bio_faqpost_author_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
