# Generated by Django 5.2.9 on 2026-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_faqpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpost',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
