# Generated by Django 5.2.9 on 2026-01-08

from django.db import migrations

def create_demo_blog(apps, schema_editor):
    BlogCategory = apps.get_model('core', 'BlogCategory')
    BlogPost = apps.get_model('core', 'BlogPost')
    # Create a root category if not exists
    cat, _ = BlogCategory.objects.get_or_create(
        slug='general',
        defaults={'name': 'General', 'order': 0, 'is_active': True, 'parent': None}
    )
    # Create a demo post with slug 'test' so the preview link works
    BlogPost.objects.get_or_create(
        slug='test',
        defaults={
            'title': 'Test Post',
            'category': cat,
            'summary': 'A sample article to verify blog routing.',
            'content': '<p>This is a demo blog post. You can edit or delete it from the admin.</p>',
            'order': 0,
            'is_active': True,
            'meta_title': 'Test Post',
            'meta_description': 'Demo blog post used for routing verification.',
            'meta_keywords': 'demo, test, blog',
            'author_name': 'Admin',
        }
    )

def remove_demo_blog(apps, schema_editor):
    BlogPost = apps.get_model('core', 'BlogPost')
    BlogCategory = apps.get_model('core', 'BlogCategory')
    try:
        post = BlogPost.objects.get(slug='test')
        post.delete()
    except BlogPost.DoesNotExist:
        pass
    # Optionally remove category if empty
    try:
        cat = BlogCategory.objects.get(slug='general')
        if not cat.posts.exists():
            cat.delete()
    except BlogCategory.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blogcategory_blogpost'),
    ]

    operations = [
        migrations.RunPython(create_demo_blog, reverse_code=remove_demo_blog),
    ]
