# Generated by Django 5.2.9 on 2026-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_blog_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='show_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
