# Generated by Django 5.2.9 on 2026-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_blogcategory_is_dropdown_blogcategory_show_in_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
