# Generated by Django 5.2.9 on 2026-01-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_blogcategory_show_in_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='nav_group',
            field=models.CharField(blank=True, choices=[('', 'None'), ('quotes', 'Compare Quotes'), ('companies', 'Companies'), ('cost', 'Coverage & Cost'), ('save', 'Ways to Save'), ('resources', 'Resources & FAQs')], default='', max_length=20),
        ),
    ]
