# Generated by Django 5.2.9 on 2026-01-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogcategory_nav_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
