# Generated by Django 5.2.9 on 2026-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_company_is_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='core.company'),
        ),
    ]
