# Generated by Django 5.2.9 on 2026-01-08 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_faqcategory_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.company'),
        ),
    ]
