# Generated by Django 5.2.9 on 2026-01-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]

