# Generated by Django 5.2.9 on 2026-01-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_seed_blog_posts_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quick FAQ',
                'verbose_name_plural': 'Quick FAQs',
                'ordering': ['order', 'question'],
            },
        ),
    ]
