# Generated by Django 5.2.9 on 2026-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_quickfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='icon',
            field=models.ImageField(blank=True, help_text="Icon for 'Explore Popular Topics' section", upload_to='blog/icons/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Check this to show in 'Explore Popular Topics' section on home page"),
        ),
    ]
