# Generated by Django 5.2.9 on 2026-01-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_blogpost_icon_blogpost_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show_in_guides',
            field=models.BooleanField(default=False, help_text="Check to show in 'Guides' section on home page"),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_in_recommendations',
            field=models.BooleanField(default=False, help_text="Check to show in 'Our Top Recommendations' / 'Recommendations' section on home page"),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_in_research',
            field=models.BooleanField(default=False, help_text="Check to show in 'Driving Research' section on home page"),
        ),
    ]
