# Generated by Django 5.2.9 on 2026-01-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_seed_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='site_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.siteconfig'),
        ),
    ]
