# Generated by Django 5.2.9 on 2026-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_announcement_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='btn_text',
            field=models.CharField(default='View My Quote', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='heading',
            field=models.CharField(blank=True, help_text='e.g. TN Drivers Could Save Big with GEICO', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_heading_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_heading_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_heading_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='zip_codes', to='core.company')),
            ],
        ),
    ]
