# Generated by Django 5.2.9 on 2026-01-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_company_btn_text_company_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_zip', models.IntegerField(help_text='Start of the zip code range (e.g., 38000)')),
                ('end_zip', models.IntegerField(help_text='End of the zip code range (e.g., 38050)')),
                ('companies', models.ManyToManyField(blank=True, related_name='zip_ranges', to='core.company')),
            ],
            options={
                'verbose_name': 'Zip Code Range',
                'verbose_name_plural': 'Zip Code Ranges',
                'ordering': ['start_zip'],
            },
        ),
    ]
