# Generated by Django 5.2.9 on 2026-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_ziprange_options_ziprange_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='2-letter state code (e.g., CA)', max_length=2, unique=True)),
                ('name', models.CharField(help_text='Full state name (e.g., California)', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='companies', to='core.state'),
        ),
    ]
