# Generated by Django 5.2.9 on 2026-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_enable_footer_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='youtube_channel_name',
            field=models.CharField(blank=True, help_text='e.g. @AutoInsuranceExperts', max_length=100),
        ),
    ]
