# Generated by Django 5.2.9 on 2026-01-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_siteconfig_youtube_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_top_pick',
        ),
        migrations.CreateModel(
            name='ZipRangeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_top_pick', models.BooleanField(default=False, verbose_name='Is Top Pick?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('zip_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ziprange')),
            ],
            options={
                'verbose_name': 'Zip Range Company',
                'verbose_name_plural': 'Zip Range Companies',
                'unique_together': {('zip_range', 'company')},
            },
        ),
    ]
