# Generated by Django 5.2.9 on 2026-01-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_company_is_top_pick_ziprangecompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziprange',
            name='companies',
        ),
    ]
