# Generated by Django 5.2.9 on 2026-01-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_ziprange_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziprange',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='zip_ranges', through='core.ZipRangeCompany', to='core.company'),
        ),
    ]
